# Generated by Django 3.2 on 2021-10-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamvilla_mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell_property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Property_Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
                ('Property_Description', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=30)),
                ('Bedrooms', models.CharField(max_length=30)),
                ('Bathrooms', models.CharField(max_length=30)),
                ('Garages', models.CharField(max_length=30)),
                ('rent_or_sell', models.CharField(max_length=30)),
                ('facilities', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='userimages')),
            ],
        ),
    ]
