# Generated by Django 3.2 on 2022-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamvilla_mainapp', '0002_sell_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell_property1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Property_Name', models.CharField(max_length=30)),
                ('photo1', models.ImageField(upload_to='userimages')),
                ('photo2', models.ImageField(upload_to='userimages')),
                ('photo3', models.ImageField(upload_to='userimages')),
            ],
        ),
    ]
